FROM ubuntu:latest

# Update APT package index
RUN apt-get update

# Upgrade currently installed software
RUN apt-get upgrade -y

# Set the default command to echo "Hello, World!"
CMD ["echo", "Hello, World!"]